In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience = df.experience.fillna('zero')
df  

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
df['experience'].iloc[:2] = "zero"

In [18]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].median())
median_test_score

8

In [21]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

In [22]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [27]:
from word2number import w2n

In [35]:
list = df['experience'].Series()

AttributeError: 'Series' object has no attribute 'Series'

In [44]:
mylist = []
for item in df['experience'].iloc[:len(df)]:
     mylist.append(w2n.word_to_num(item))

In [45]:
mylist

[0, 0, 5, 2, 7, 3, 10, 11]

In [46]:
df['experience'] = mylist

In [47]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [52]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience' , 'test_score(out of 10)' ,'interview_score(out of 10)']] , df['salary($)'])

LinearRegression()

In [53]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [54]:
reg.intercept_

17737.26346433771

In [55]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [56]:
reg.predict([[12,10,10]])

array([92002.18340611])